/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as models from "../models";

export class FeedbackTasks extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * List feedback tasks.
     */
    async list(options?: RequestOptions): Promise<models.ListFeedbackTasksResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const path$ = this.templateURLComponent("/api/v1/feedback_task")();

        const query$ = "";

        let security$;
        if (typeof this.options$.log10Token === "function") {
            security$ = { log10Token: await this.options$.log10Token() };
        } else if (this.options$.log10Token) {
            security$ = { log10Token: this.options$.log10Token };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "listFeedbackTasks",
            oAuth2Scopes: [],
            securitySource: this.options$.log10Token,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<models.ListFeedbackTasksResponse>()
            .json(200, models.ListFeedbackTasksResponse$, { key: "Tasks" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Create a new task.
     */
    async create(
        request?: models.Task | undefined,
        options?: RequestOptions
    ): Promise<models.CreateFeedbackTaskResponse> {
        const input$ = request;
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.Task$.outboundSchema.optional().parse(value$),
            "Input validation failed"
        );
        const body$ =
            payload$ === undefined ? null : enc$.encodeJSON("body", payload$, { explode: true });

        const path$ = this.templateURLComponent("/api/v1/feedback_task")();

        const query$ = "";

        let security$;
        if (typeof this.options$.log10Token === "function") {
            security$ = { log10Token: await this.options$.log10Token() };
        } else if (this.options$.log10Token) {
            security$ = { log10Token: this.options$.log10Token };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "createFeedbackTask",
            oAuth2Scopes: [],
            securitySource: this.options$.log10Token,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<models.CreateFeedbackTaskResponse>()
            .json(200, models.CreateFeedbackTaskResponse$, { key: "Task" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Retrieves feedback task `taskId`.
     */
    async get(taskId: string, options?: RequestOptions): Promise<models.GetFeedbackTaskResponse> {
        const input$: models.GetFeedbackTaskRequest = {
            taskId: taskId,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => models.GetFeedbackTaskRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            taskId: enc$.encodeSimple("taskId", payload$.taskId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/v1/feedback_task/{taskId}")(pathParams$);

        const query$ = "";

        let security$;
        if (typeof this.options$.log10Token === "function") {
            security$ = { log10Token: await this.options$.log10Token() };
        } else if (this.options$.log10Token) {
            security$ = { log10Token: this.options$.log10Token };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "getFeedbackTask",
            oAuth2Scopes: [],
            securitySource: this.options$.log10Token,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<models.GetFeedbackTaskResponse>()
            .json(200, models.GetFeedbackTaskResponse$, { key: "Task" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
