/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as operations from "../models/operations";

export class Feedback extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Fetch feedback by id.
     */
    async get(
        feedbackId: string,
        xLog10Organization?: string | undefined,
        options?: RequestOptions
    ): Promise<operations.GetResponse> {
        const input$: operations.GetRequest = {
            feedbackId: feedbackId,
            xLog10Organization: xLog10Organization,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.GetRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = null;

        const pathParams$ = {
            feedbackId: enc$.encodeSimple("feedbackId", payload$.feedbackId, {
                explode: false,
                charEncoding: "percent",
            }),
        };
        const path$ = this.templateURLComponent("/api/v1/feedback/{feedbackId}")(pathParams$);

        const query$ = "";

        headers$.set(
            "X-Log10-Organization",
            enc$.encodeSimple(
                "X-Log10-Organization",
                payload$["X-Log10-Organization"] ?? this.options$.xLog10Organization,
                { explode: false, charEncoding: "none" }
            )
        );

        let security$;
        if (typeof this.options$.log10Token === "function") {
            security$ = { log10Token: await this.options$.log10Token() };
        } else if (this.options$.log10Token) {
            security$ = { log10Token: this.options$.log10Token };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "get",
            oAuth2Scopes: [],
            securitySource: this.options$.log10Token,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "GET",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.GetResponse>()
            .json(200, operations.GetResponse$, { key: "Feedback" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }

    /**
     * Upload a piece of feedback
     */
    async upload(
        requestBody: operations.UploadRequestBody,
        xLog10Organization?: string | undefined,
        options?: RequestOptions
    ): Promise<operations.UploadResponse> {
        const input$: operations.UploadRequest = {
            xLog10Organization: xLog10Organization,
            requestBody: requestBody,
        };
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.UploadRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = enc$.encodeJSON("body", payload$.RequestBody, { explode: true });

        const path$ = this.templateURLComponent("/api/v1/feedback")();

        const query$ = "";

        headers$.set(
            "X-Log10-Organization",
            enc$.encodeSimple(
                "X-Log10-Organization",
                payload$["X-Log10-Organization"] ?? this.options$.xLog10Organization,
                { explode: false, charEncoding: "none" }
            )
        );

        let security$;
        if (typeof this.options$.log10Token === "function") {
            security$ = { log10Token: await this.options$.log10Token() };
        } else if (this.options$.log10Token) {
            security$ = { log10Token: this.options$.log10Token };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "upload",
            oAuth2Scopes: [],
            securitySource: this.options$.log10Token,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<operations.UploadResponse>()
            .json(200, operations.UploadResponse$, { key: "Feedback" })
            .fail(["4XX", "5XX"])
            .match(response, request$, { extraFields: responseFields$ });

        return result$;
    }
}
