/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedbackGet } from "../funcs/feedbackGet.js";
import { feedbackUpload } from "../funcs/feedbackUpload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FeedbackSDK extends ClientSDK {
  /**
   * Fetch feedback by id.
   */
  async get(
    feedbackId: string,
    xLog10Organization?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.GetResponse> {
    return unwrapAsync(feedbackGet(
      this,
      feedbackId,
      xLog10Organization,
      options,
    ));
  }

  /**
   * Upload a piece of feedback
   */
  async upload(
    requestBody: models.UploadRequestBody,
    xLog10Organization?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.UploadResponse> {
    return unwrapAsync(feedbackUpload(
      this,
      requestBody,
      xLog10Organization,
      options,
    ));
  }
}
