/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Completions } from "./completions.js";
import { FeedbackSDK } from "./feedbacksdk.js";
import { FeedbackTasks } from "./feedbacktasks.js";
import { Sessions } from "./sessions.js";

export class Log10 extends ClientSDK {
    private _completions?: Completions;
    get completions(): Completions {
        return (this._completions ??= new Completions(this.options$));
    }

    private _sessions?: Sessions;
    get sessions(): Sessions {
        return (this._sessions ??= new Sessions(this.options$));
    }

    private _feedbackSDK?: FeedbackSDK;
    get feedbackSDK(): FeedbackSDK {
        return (this._feedbackSDK ??= new FeedbackSDK(this.options$));
    }

    private _feedbackTasks?: FeedbackTasks;
    get feedbackTasks(): FeedbackTasks {
        return (this._feedbackTasks ??= new FeedbackTasks(this.options$));
    }
}
