/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Completions } from "./completions";
import { FeedbackSDK } from "./feedbacksdk";
import { FeedbackTasks } from "./feedbacktasks";
import { Sessions } from "./sessions";

export class Log10 extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    private _completions?: Completions;
    get completions(): Completions {
        return (this._completions ??= new Completions(this.options$));
    }

    private _sessions?: Sessions;
    get sessions(): Sessions {
        return (this._sessions ??= new Sessions(this.options$));
    }

    private _feedbackSDK?: FeedbackSDK;
    get feedbackSDK(): FeedbackSDK {
        return (this._feedbackSDK ??= new FeedbackSDK(this.options$));
    }

    private _feedbackTasks?: FeedbackTasks;
    get feedbackTasks(): FeedbackTasks {
        return (this._feedbackTasks ??= new FeedbackTasks(this.options$));
    }
}
