/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsCreate } from "../funcs/sessionsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sessions extends ClientSDK {
  /**
   * Create a session
   */
  async create(
    xLog10Organization?: string | undefined,
    options?: RequestOptions,
  ): Promise<models.CreateSessionResponse> {
    return unwrapAsync(sessionsCreate(
      this,
      xLog10Organization,
      options,
    ));
  }
}
