/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type CreateGlobals = {
    xLog10Organization: string;
};

export type CreateRequest = {
    xLog10Organization?: string | undefined;
    completion: components.Completion;
};

export type CreateResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Created
     */
    any?: any | undefined;
    /**
     * Created
     */
    completion?: components.Completion | undefined;
};

/** @internal */
export namespace CreateGlobals$ {
    export const inboundSchema: z.ZodType<CreateGlobals, z.ZodTypeDef, unknown> = z
        .object({
            "X-Log10-Organization": z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                "X-Log10-Organization": "xLog10Organization",
            });
        });

    export type Outbound = {
        "X-Log10-Organization": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateGlobals> = z
        .object({
            xLog10Organization: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                xLog10Organization: "X-Log10-Organization",
            });
        });
}

/** @internal */
export namespace CreateRequest$ {
    export const inboundSchema: z.ZodType<CreateRequest, z.ZodTypeDef, unknown> = z
        .object({
            "X-Log10-Organization": z.string().optional(),
            Completion: components.Completion$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                "X-Log10-Organization": "xLog10Organization",
                Completion: "completion",
            });
        });

    export type Outbound = {
        "X-Log10-Organization"?: string | undefined;
        Completion: components.Completion$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateRequest> = z
        .object({
            xLog10Organization: z.string().optional(),
            completion: components.Completion$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                xLog10Organization: "X-Log10-Organization",
                completion: "Completion",
            });
        });
}

/** @internal */
export namespace CreateResponse$ {
    export const inboundSchema: z.ZodType<CreateResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            any: z.any().optional(),
            Completion: components.Completion$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Completion: "completion",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        any?: any | undefined;
        Completion?: components.Completion$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            any: z.any().optional(),
            completion: components.Completion$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                completion: "Completion",
            });
        });
}
