/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    ChatCompletionRequestMessageContentPartImage,
    ChatCompletionRequestMessageContentPartImage$,
} from "./chatcompletionrequestmessagecontentpartimage.js";
import {
    ChatCompletionRequestMessageContentPartText,
    ChatCompletionRequestMessageContentPartText$,
} from "./chatcompletionrequestmessagecontentparttext.js";
import * as z from "zod";

export type ChatCompletionRequestMessageContentPart =
    | ChatCompletionRequestMessageContentPartText
    | ChatCompletionRequestMessageContentPartImage;

/** @internal */
export namespace ChatCompletionRequestMessageContentPart$ {
    export const inboundSchema: z.ZodType<
        ChatCompletionRequestMessageContentPart,
        z.ZodTypeDef,
        unknown
    > = z.union([
        ChatCompletionRequestMessageContentPartText$.inboundSchema,
        ChatCompletionRequestMessageContentPartImage$.inboundSchema,
    ]);

    export type Outbound =
        | ChatCompletionRequestMessageContentPartText$.Outbound
        | ChatCompletionRequestMessageContentPartImage$.Outbound;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ChatCompletionRequestMessageContentPart
    > = z.union([
        ChatCompletionRequestMessageContentPartText$.outboundSchema,
        ChatCompletionRequestMessageContentPartImage$.outboundSchema,
    ]);
}
