/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    ChatCompletionRole,
    ChatCompletionRole$inboundSchema,
    ChatCompletionRole$outboundSchema,
} from "./chatcompletionrole.js";
import * as z from "zod";

/**
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type ChatCompletionRequestFunctionMessage = {
    /**
     * The role of the author of a message
     */
    role: ChatCompletionRole;
    /**
     * The contents of the function message.
     */
    content: string | null;
    /**
     * The name of the function to call.
     */
    name: string;
};

/** @internal */
export const ChatCompletionRequestFunctionMessage$inboundSchema: z.ZodType<
    ChatCompletionRequestFunctionMessage,
    z.ZodTypeDef,
    unknown
> = z.object({
    role: ChatCompletionRole$inboundSchema,
    content: z.nullable(z.string()),
    name: z.string(),
});

/** @internal */
export type ChatCompletionRequestFunctionMessage$Outbound = {
    role: string;
    content: string | null;
    name: string;
};

/** @internal */
export const ChatCompletionRequestFunctionMessage$outboundSchema: z.ZodType<
    ChatCompletionRequestFunctionMessage$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestFunctionMessage
> = z.object({
    role: ChatCompletionRole$outboundSchema,
    content: z.nullable(z.string()),
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionRequestFunctionMessage$ {
    /** @deprecated use `ChatCompletionRequestFunctionMessage$inboundSchema` instead. */
    export const inboundSchema = ChatCompletionRequestFunctionMessage$inboundSchema;
    /** @deprecated use `ChatCompletionRequestFunctionMessage$outboundSchema` instead. */
    export const outboundSchema = ChatCompletionRequestFunctionMessage$outboundSchema;
    /** @deprecated use `ChatCompletionRequestFunctionMessage$Outbound` instead. */
    export type Outbound = ChatCompletionRequestFunctionMessage$Outbound;
}
