/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ChatCompletionRole, ChatCompletionRole$ } from "./chatcompletionrole.js";
import * as z from "zod";

/**
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type ChatCompletionRequestFunctionMessage = {
    /**
     * The role of the author of a message
     */
    role: ChatCompletionRole;
    /**
     * The contents of the function message.
     */
    content: string | null;
    /**
     * The name of the function to call.
     */
    name: string;
};

/** @internal */
export namespace ChatCompletionRequestFunctionMessage$ {
    export const inboundSchema: z.ZodType<
        ChatCompletionRequestFunctionMessage,
        z.ZodTypeDef,
        unknown
    > = z.object({
        role: ChatCompletionRole$.inboundSchema,
        content: z.nullable(z.string()),
        name: z.string(),
    });

    export type Outbound = {
        role: string;
        content: string | null;
        name: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ChatCompletionRequestFunctionMessage
    > = z.object({
        role: ChatCompletionRole$.outboundSchema,
        content: z.nullable(z.string()),
        name: z.string(),
    });
}
