/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import * as z from "zod";

/**
 * Options for streaming response. Only set this when you set `stream: true`.
 *
 * @remarks
 *
 */
export type ChatCompletionStreamOptions = {
    /**
     * If set, an additional chunk will be streamed before the `data: [DONE]` message. The `usage` field on this chunk shows the token usage statistics for the entire request, and the `choices` field will always be an empty array. All other chunks will also include a `usage` field, but with a null value.
     *
     * @remarks
     *
     */
    includeUsage?: boolean | undefined;
};

/** @internal */
export namespace ChatCompletionStreamOptions$ {
    export const inboundSchema: z.ZodType<ChatCompletionStreamOptions, z.ZodTypeDef, unknown> = z
        .object({
            include_usage: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                include_usage: "includeUsage",
            });
        });

    export type Outbound = {
        include_usage?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ChatCompletionStreamOptions> = z
        .object({
            includeUsage: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                includeUsage: "include_usage",
            });
        });
}
