/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChatCompletionRole,
  ChatCompletionRole$inboundSchema,
  ChatCompletionRole$outboundSchema,
} from "./chatcompletionrole.js";

export type ChatCompletionRequestSystemMessage = {
  /**
   * The contents of the system message.
   */
  content: string;
  /**
   * The role of the author of a message
   */
  role: ChatCompletionRole;
  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestSystemMessage$inboundSchema: z.ZodType<
  ChatCompletionRequestSystemMessage,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string(),
  role: ChatCompletionRole$inboundSchema,
  name: z.string().optional(),
});

/** @internal */
export type ChatCompletionRequestSystemMessage$Outbound = {
  content: string;
  role: string;
  name?: string | undefined;
};

/** @internal */
export const ChatCompletionRequestSystemMessage$outboundSchema: z.ZodType<
  ChatCompletionRequestSystemMessage$Outbound,
  z.ZodTypeDef,
  ChatCompletionRequestSystemMessage
> = z.object({
  content: z.string(),
  role: ChatCompletionRole$outboundSchema,
  name: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionRequestSystemMessage$ {
  /** @deprecated use `ChatCompletionRequestSystemMessage$inboundSchema` instead. */
  export const inboundSchema = ChatCompletionRequestSystemMessage$inboundSchema;
  /** @deprecated use `ChatCompletionRequestSystemMessage$outboundSchema` instead. */
  export const outboundSchema =
    ChatCompletionRequestSystemMessage$outboundSchema;
  /** @deprecated use `ChatCompletionRequestSystemMessage$Outbound` instead. */
  export type Outbound = ChatCompletionRequestSystemMessage$Outbound;
}
