/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of the tool. Currently, only `function` is supported.
 */
export enum ChatCompletionNamedToolChoiceType {
    Function = "function",
}

export type ChatCompletionNamedToolChoiceFunction = {
    /**
     * The name of the function to call.
     */
    name: string;
};

/**
 * Specifies a tool the model should use. Use to force the model to call a specific function.
 */
export type ChatCompletionNamedToolChoice = {
    /**
     * The type of the tool. Currently, only `function` is supported.
     */
    type: ChatCompletionNamedToolChoiceType;
    function: ChatCompletionNamedToolChoiceFunction;
};

/** @internal */
export const ChatCompletionNamedToolChoiceType$inboundSchema: z.ZodNativeEnum<
    typeof ChatCompletionNamedToolChoiceType
> = z.nativeEnum(ChatCompletionNamedToolChoiceType);

/** @internal */
export const ChatCompletionNamedToolChoiceType$outboundSchema: z.ZodNativeEnum<
    typeof ChatCompletionNamedToolChoiceType
> = ChatCompletionNamedToolChoiceType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionNamedToolChoiceType$ {
    /** @deprecated use `ChatCompletionNamedToolChoiceType$inboundSchema` instead. */
    export const inboundSchema = ChatCompletionNamedToolChoiceType$inboundSchema;
    /** @deprecated use `ChatCompletionNamedToolChoiceType$outboundSchema` instead. */
    export const outboundSchema = ChatCompletionNamedToolChoiceType$outboundSchema;
}

/** @internal */
export const ChatCompletionNamedToolChoiceFunction$inboundSchema: z.ZodType<
    ChatCompletionNamedToolChoiceFunction,
    z.ZodTypeDef,
    unknown
> = z.object({
    name: z.string(),
});

/** @internal */
export type ChatCompletionNamedToolChoiceFunction$Outbound = {
    name: string;
};

/** @internal */
export const ChatCompletionNamedToolChoiceFunction$outboundSchema: z.ZodType<
    ChatCompletionNamedToolChoiceFunction$Outbound,
    z.ZodTypeDef,
    ChatCompletionNamedToolChoiceFunction
> = z.object({
    name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionNamedToolChoiceFunction$ {
    /** @deprecated use `ChatCompletionNamedToolChoiceFunction$inboundSchema` instead. */
    export const inboundSchema = ChatCompletionNamedToolChoiceFunction$inboundSchema;
    /** @deprecated use `ChatCompletionNamedToolChoiceFunction$outboundSchema` instead. */
    export const outboundSchema = ChatCompletionNamedToolChoiceFunction$outboundSchema;
    /** @deprecated use `ChatCompletionNamedToolChoiceFunction$Outbound` instead. */
    export type Outbound = ChatCompletionNamedToolChoiceFunction$Outbound;
}

/** @internal */
export const ChatCompletionNamedToolChoice$inboundSchema: z.ZodType<
    ChatCompletionNamedToolChoice,
    z.ZodTypeDef,
    unknown
> = z.object({
    type: ChatCompletionNamedToolChoiceType$inboundSchema,
    function: z.lazy(() => ChatCompletionNamedToolChoiceFunction$inboundSchema),
});

/** @internal */
export type ChatCompletionNamedToolChoice$Outbound = {
    type: string;
    function: ChatCompletionNamedToolChoiceFunction$Outbound;
};

/** @internal */
export const ChatCompletionNamedToolChoice$outboundSchema: z.ZodType<
    ChatCompletionNamedToolChoice$Outbound,
    z.ZodTypeDef,
    ChatCompletionNamedToolChoice
> = z.object({
    type: ChatCompletionNamedToolChoiceType$outboundSchema,
    function: z.lazy(() => ChatCompletionNamedToolChoiceFunction$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionNamedToolChoice$ {
    /** @deprecated use `ChatCompletionNamedToolChoice$inboundSchema` instead. */
    export const inboundSchema = ChatCompletionNamedToolChoice$inboundSchema;
    /** @deprecated use `ChatCompletionNamedToolChoice$outboundSchema` instead. */
    export const outboundSchema = ChatCompletionNamedToolChoice$outboundSchema;
    /** @deprecated use `ChatCompletionNamedToolChoice$Outbound` instead. */
    export type Outbound = ChatCompletionNamedToolChoice$Outbound;
}
