/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    ChatCompletionRequestMessageContentPartImage,
    ChatCompletionRequestMessageContentPartImage$inboundSchema,
    ChatCompletionRequestMessageContentPartImage$Outbound,
    ChatCompletionRequestMessageContentPartImage$outboundSchema,
} from "./chatcompletionrequestmessagecontentpartimage.js";
import {
    ChatCompletionRequestMessageContentPartText,
    ChatCompletionRequestMessageContentPartText$inboundSchema,
    ChatCompletionRequestMessageContentPartText$Outbound,
    ChatCompletionRequestMessageContentPartText$outboundSchema,
} from "./chatcompletionrequestmessagecontentparttext.js";
import * as z from "zod";

export type ChatCompletionRequestMessageContentPart =
    | ChatCompletionRequestMessageContentPartText
    | ChatCompletionRequestMessageContentPartImage;

/** @internal */
export const ChatCompletionRequestMessageContentPart$inboundSchema: z.ZodType<
    ChatCompletionRequestMessageContentPart,
    z.ZodTypeDef,
    unknown
> = z.union([
    ChatCompletionRequestMessageContentPartText$inboundSchema,
    ChatCompletionRequestMessageContentPartImage$inboundSchema,
]);

/** @internal */
export type ChatCompletionRequestMessageContentPart$Outbound =
    | ChatCompletionRequestMessageContentPartText$Outbound
    | ChatCompletionRequestMessageContentPartImage$Outbound;

/** @internal */
export const ChatCompletionRequestMessageContentPart$outboundSchema: z.ZodType<
    ChatCompletionRequestMessageContentPart$Outbound,
    z.ZodTypeDef,
    ChatCompletionRequestMessageContentPart
> = z.union([
    ChatCompletionRequestMessageContentPartText$outboundSchema,
    ChatCompletionRequestMessageContentPartImage$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ChatCompletionRequestMessageContentPart$ {
    /** @deprecated use `ChatCompletionRequestMessageContentPart$inboundSchema` instead. */
    export const inboundSchema = ChatCompletionRequestMessageContentPart$inboundSchema;
    /** @deprecated use `ChatCompletionRequestMessageContentPart$outboundSchema` instead. */
    export const outboundSchema = ChatCompletionRequestMessageContentPart$outboundSchema;
    /** @deprecated use `ChatCompletionRequestMessageContentPart$Outbound` instead. */
    export type Outbound = ChatCompletionRequestMessageContentPart$Outbound;
}
