/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../lib/primitives.js";
import {
    CreateChatCompletionRequest,
    CreateChatCompletionRequest$,
} from "./createchatcompletionrequest.js";
import {
    CreateChatCompletionResponse,
    CreateChatCompletionResponse$,
} from "./createchatcompletionresponse.js";
import * as z from "zod";

/**
 * The kind of completion i.e. chat messages or prompt
 */
export enum Kind {
    Chat = "chat",
    Prompt = "prompt",
}

/**
 * The status of this completion.
 */
export enum Status {
    Started = "started",
    Finished = "finished",
    Failed = "failed",
}

export type Stacktrace = {
    /**
     * The file associated with this stacktrace.
     */
    file: string;
    /**
     * The line associated with this stacktrace.
     */
    line: string;
    /**
     * The line number associated with this stacktrace.
     */
    lineno: number;
    /**
     * The function or module associated with this stacktrace.
     */
    name: string;
};

export type Completion = {
    /**
     * The unique identifier for this task.
     */
    id?: string | undefined;
    /**
     * The unique identifier for the organization.
     */
    organizationId: string;
    /**
     * The kind of completion i.e. chat messages or prompt
     */
    kind: Kind;
    /**
     * The status of this completion.
     */
    status?: Status | undefined;
    /**
     * The tags for this completion.
     */
    tags?: Array<string> | undefined;
    request?: CreateChatCompletionRequest | undefined;
    /**
     * Represents a chat completion response returned by model, based on the provided input.
     */
    response?: CreateChatCompletionResponse | undefined;
    /**
     * The stacktrace for this completion.
     */
    stacktrace?: Array<Stacktrace> | undefined;
    /**
     * The session id for this completion.
     */
    sessionId?: string | undefined;
    /**
     * The duration of this completion in seconds.
     */
    duration?: number | undefined;
    /**
     * The failure kind of this completion.
     */
    failureKind?: string | undefined;
    /**
     * The failure reason of this completion.
     */
    failureReason?: string | undefined;
};

/** @internal */
export namespace Kind$ {
    export const inboundSchema: z.ZodNativeEnum<typeof Kind> = z.nativeEnum(Kind);
    export const outboundSchema: z.ZodNativeEnum<typeof Kind> = inboundSchema;
}

/** @internal */
export namespace Status$ {
    export const inboundSchema: z.ZodNativeEnum<typeof Status> = z.nativeEnum(Status);
    export const outboundSchema: z.ZodNativeEnum<typeof Status> = inboundSchema;
}

/** @internal */
export namespace Stacktrace$ {
    export const inboundSchema: z.ZodType<Stacktrace, z.ZodTypeDef, unknown> = z.object({
        file: z.string(),
        line: z.string(),
        lineno: z.number(),
        name: z.string(),
    });

    export type Outbound = {
        file: string;
        line: string;
        lineno: number;
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Stacktrace> = z.object({
        file: z.string(),
        line: z.string(),
        lineno: z.number(),
        name: z.string(),
    });
}

/** @internal */
export namespace Completion$ {
    export const inboundSchema: z.ZodType<Completion, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string().optional(),
            organization_id: z.string(),
            kind: Kind$.inboundSchema,
            status: Status$.inboundSchema.optional(),
            tags: z.array(z.string()).optional(),
            request: CreateChatCompletionRequest$.inboundSchema.optional(),
            response: CreateChatCompletionResponse$.inboundSchema.optional(),
            stacktrace: z.array(z.lazy(() => Stacktrace$.inboundSchema)).optional(),
            session_id: z.string().optional(),
            duration: z.number().optional(),
            failure_kind: z.string().optional(),
            failure_reason: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                organization_id: "organizationId",
                session_id: "sessionId",
                failure_kind: "failureKind",
                failure_reason: "failureReason",
            });
        });

    export type Outbound = {
        id?: string | undefined;
        organization_id: string;
        kind: string;
        status?: string | undefined;
        tags?: Array<string> | undefined;
        request?: CreateChatCompletionRequest$.Outbound | undefined;
        response?: CreateChatCompletionResponse$.Outbound | undefined;
        stacktrace?: Array<Stacktrace$.Outbound> | undefined;
        session_id?: string | undefined;
        duration?: number | undefined;
        failure_kind?: string | undefined;
        failure_reason?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Completion> = z
        .object({
            id: z.string().optional(),
            organizationId: z.string(),
            kind: Kind$.outboundSchema,
            status: Status$.outboundSchema.optional(),
            tags: z.array(z.string()).optional(),
            request: CreateChatCompletionRequest$.outboundSchema.optional(),
            response: CreateChatCompletionResponse$.outboundSchema.optional(),
            stacktrace: z.array(z.lazy(() => Stacktrace$.outboundSchema)).optional(),
            sessionId: z.string().optional(),
            duration: z.number().optional(),
            failureKind: z.string().optional(),
            failureReason: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                organizationId: "organization_id",
                sessionId: "session_id",
                failureKind: "failure_kind",
                failureReason: "failure_reason",
            });
        });
}
