/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Completion, Completion$ } from "./completion";
import { HTTPMetadata, HTTPMetadata$ } from "./httpmetadata";
import * as z from "zod";

export type CreateGlobals = {
    xLog10Organization: string;
};

export type CreateRequest = {
    xLog10Organization?: string | undefined;
    completion: Completion;
};

export type CreateResponse = {
    httpMeta: HTTPMetadata;
    /**
     * Created
     */
    any?: any | undefined;
    /**
     * Created
     */
    completion?: Completion | undefined;
};

/** @internal */
export namespace CreateGlobals$ {
    export const inboundSchema: z.ZodType<CreateGlobals, z.ZodTypeDef, unknown> = z
        .object({
            "X-Log10-Organization": z.string(),
        })
        .transform((v) => {
            return {
                xLog10Organization: v["X-Log10-Organization"],
            };
        });

    export type Outbound = {
        "X-Log10-Organization": string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateGlobals> = z
        .object({
            xLog10Organization: z.string(),
        })
        .transform((v) => {
            return {
                "X-Log10-Organization": v.xLog10Organization,
            };
        });
}

/** @internal */
export namespace CreateRequest$ {
    export const inboundSchema: z.ZodType<CreateRequest, z.ZodTypeDef, unknown> = z
        .object({
            "X-Log10-Organization": z.string().optional(),
            Completion: Completion$.inboundSchema,
        })
        .transform((v) => {
            return {
                ...(v["X-Log10-Organization"] === undefined
                    ? null
                    : { xLog10Organization: v["X-Log10-Organization"] }),
                completion: v.Completion,
            };
        });

    export type Outbound = {
        "X-Log10-Organization"?: string | undefined;
        Completion: Completion$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateRequest> = z
        .object({
            xLog10Organization: z.string().optional(),
            completion: Completion$.outboundSchema,
        })
        .transform((v) => {
            return {
                ...(v.xLog10Organization === undefined
                    ? null
                    : { "X-Log10-Organization": v.xLog10Organization }),
                Completion: v.completion,
            };
        });
}

/** @internal */
export namespace CreateResponse$ {
    export const inboundSchema: z.ZodType<CreateResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: HTTPMetadata$.inboundSchema,
            any: z.any().optional(),
            Completion: Completion$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.any === undefined ? null : { any: v.any }),
                ...(v.Completion === undefined ? null : { completion: v.Completion }),
            };
        });

    export type Outbound = {
        HttpMeta: HTTPMetadata$.Outbound;
        any?: any | undefined;
        Completion?: Completion$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateResponse> = z
        .object({
            httpMeta: HTTPMetadata$.outboundSchema,
            any: z.any().optional(),
            completion: Completion$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.any === undefined ? null : { any: v.any }),
                ...(v.completion === undefined ? null : { Completion: v.completion }),
            };
        });
}
