/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { HTTPMetadata, HTTPMetadata$ } from "./httpmetadata";
import { Task, Task$ } from "./task";
import * as z from "zod";

export type CreateFeedbackTaskResponse = {
    httpMeta: HTTPMetadata;
    /**
     * OK
     */
    task?: Task | undefined;
};

/** @internal */
export namespace CreateFeedbackTaskResponse$ {
    export const inboundSchema: z.ZodType<CreateFeedbackTaskResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: HTTPMetadata$.inboundSchema,
            Task: Task$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Task === undefined ? null : { task: v.Task }),
            };
        });

    export type Outbound = {
        HttpMeta: HTTPMetadata$.Outbound;
        Task?: Task$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateFeedbackTaskResponse> = z
        .object({
            httpMeta: HTTPMetadata$.outboundSchema,
            task: Task$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.task === undefined ? null : { Task: v.task }),
            };
        });
}
