/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./sdkvalidationerror.js";

export type Task = {
  /**
   * The unique identifier for this task.
   */
  id?: string | undefined;
  /**
   * The epoch this schema was created.
   */
  createdAtMs?: number | undefined;
  /**
   * The schema of the task. Must be valid JSON Schema.
   */
  jsonSchema: { [k: string]: any };
  /**
   * The name of the task.
   */
  name: string;
  /**
   * The instructions for this task.
   */
  instruction: string;
  /**
   * The completion tag matching with this task i.e. surfaced as needing feedback.
   */
  completionTagsSelector: Array<string>;
  /**
   * The unique identifier for the organization.
   */
  organizationId: string;
};

/** @internal */
export const Task$inboundSchema: z.ZodType<Task, z.ZodTypeDef, unknown> = z
  .object({
    id: z.string().optional(),
    created_at_ms: z.number().optional(),
    json_schema: z.record(z.any()),
    name: z.string(),
    instruction: z.string(),
    completion_tags_selector: z.array(z.string()),
    organization_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "created_at_ms": "createdAtMs",
      "json_schema": "jsonSchema",
      "completion_tags_selector": "completionTagsSelector",
      "organization_id": "organizationId",
    });
  });

/** @internal */
export type Task$Outbound = {
  id?: string | undefined;
  created_at_ms?: number | undefined;
  json_schema: { [k: string]: any };
  name: string;
  instruction: string;
  completion_tags_selector: Array<string>;
  organization_id: string;
};

/** @internal */
export const Task$outboundSchema: z.ZodType<Task$Outbound, z.ZodTypeDef, Task> =
  z.object({
    id: z.string().optional(),
    createdAtMs: z.number().optional(),
    jsonSchema: z.record(z.any()),
    name: z.string(),
    instruction: z.string(),
    completionTagsSelector: z.array(z.string()),
    organizationId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      createdAtMs: "created_at_ms",
      jsonSchema: "json_schema",
      completionTagsSelector: "completion_tags_selector",
      organizationId: "organization_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Task$ {
  /** @deprecated use `Task$inboundSchema` instead. */
  export const inboundSchema = Task$inboundSchema;
  /** @deprecated use `Task$outboundSchema` instead. */
  export const outboundSchema = Task$outboundSchema;
  /** @deprecated use `Task$Outbound` instead. */
  export type Outbound = Task$Outbound;
}

export function taskToJSON(task: Task): string {
  return JSON.stringify(Task$outboundSchema.parse(task));
}

export function taskFromJSON(
  jsonString: string,
): SafeParseResult<Task, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Task$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Task' from JSON`,
  );
}
