/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    ChatCompletionFunctionCallOption,
    ChatCompletionFunctionCallOption$,
} from "./chatcompletionfunctioncalloption";
import { ChatCompletionFunctions, ChatCompletionFunctions$ } from "./chatcompletionfunctions";
import {
    ChatCompletionRequestMessage,
    ChatCompletionRequestMessage$,
} from "./chatcompletionrequestmessage";
import {
    ChatCompletionStreamOptions,
    ChatCompletionStreamOptions$,
} from "./chatcompletionstreamoptions";
import { ChatCompletionTool, ChatCompletionTool$ } from "./chatcompletiontool";
import {
    ChatCompletionToolChoiceOption,
    ChatCompletionToolChoiceOption$,
} from "./chatcompletiontoolchoiceoption";
import * as z from "zod";

export enum Two {
    Gpt4Turbo = "gpt-4-turbo",
    Gpt4Turbo20240409 = "gpt-4-turbo-2024-04-09",
    Gpt40125Preview = "gpt-4-0125-preview",
    Gpt4TurboPreview = "gpt-4-turbo-preview",
    Gpt41106Preview = "gpt-4-1106-preview",
    Gpt4VisionPreview = "gpt-4-vision-preview",
    Gpt4 = "gpt-4",
    Gpt40314 = "gpt-4-0314",
    Gpt40613 = "gpt-4-0613",
    Gpt432k = "gpt-4-32k",
    Gpt432k0314 = "gpt-4-32k-0314",
    Gpt432k0613 = "gpt-4-32k-0613",
    Gpt35Turbo = "gpt-3.5-turbo",
    Gpt35Turbo16k = "gpt-3.5-turbo-16k",
    Gpt35Turbo0301 = "gpt-3.5-turbo-0301",
    Gpt35Turbo0613 = "gpt-3.5-turbo-0613",
    Gpt35Turbo1106 = "gpt-3.5-turbo-1106",
    Gpt35Turbo0125 = "gpt-3.5-turbo-0125",
    Gpt35Turbo16k0613 = "gpt-3.5-turbo-16k-0613",
}

/**
 * ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
 */
export type Model = string | Two;

/**
 * Must be one of `text` or `json_object`.
 */
export enum CreateChatCompletionRequestType {
    Text = "text",
    JsonObject = "json_object",
}

/**
 * An object specifying the format that the model must output. Compatible with [GPT-4 Turbo](/docs/models/gpt-4-and-gpt-4-turbo) and all GPT-3.5 Turbo models newer than `gpt-3.5-turbo-1106`.
 *
 * @remarks
 *
 * Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.
 *
 * **Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request. Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.
 *
 */
export type ResponseFormat = {
    /**
     * Must be one of `text` or `json_object`.
     */
    type?: CreateChatCompletionRequestType | undefined;
};

/**
 * Up to 4 sequences where the API will stop generating further tokens.
 *
 * @remarks
 *
 */
export type Stop = string | Array<string>;

/**
 * `none` means the model will not call a function and instead generates a message. `auto` means the model can pick between generating a message or calling a function.
 *
 * @remarks
 *
 */
export enum One {
    None = "none",
    Auto = "auto",
}

/**
 * Deprecated in favor of `tool_choice`.
 *
 * @remarks
 *
 * Controls which (if any) function is called by the model.
 * `none` means the model will not call a function and instead generates a message.
 * `auto` means the model can pick between generating a message or calling a function.
 * Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
 *
 * `none` is the default when no functions are present. `auto` is the default if functions are present.
 *
 *
 * @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
 */
export type CreateChatCompletionRequestFunctionCall = ChatCompletionFunctionCallOption | One;

export type CreateChatCompletionRequest = {
    /**
     * A list of messages comprising the conversation so far. [Example Python code](https://cookbook.openai.com/examples/how_to_format_inputs_to_chatgpt_models).
     */
    messages: Array<ChatCompletionRequestMessage>;
    /**
     * ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
     */
    model: string | Two;
    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
     *
     * @remarks
     *
     * [See more information about frequency and presence penalties.](/docs/guides/text-generation/parameter-details)
     *
     */
    frequencyPenalty?: number | null | undefined;
    /**
     * Modify the likelihood of specified tokens appearing in the completion.
     *
     * @remarks
     *
     * Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
     *
     */
    logitBias?: { [k: string]: number } | null | undefined;
    /**
     * Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`.
     */
    logprobs?: boolean | null | undefined;
    /**
     * An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.
     */
    topLogprobs?: number | null | undefined;
    /**
     * The maximum number of [tokens](/tokenizer) that can be generated in the chat completion.
     *
     * @remarks
     *
     * The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken) for counting tokens.
     *
     */
    maxTokens?: number | null | undefined;
    /**
     * How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.
     */
    n?: number | null | undefined;
    /**
     * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
     *
     * @remarks
     *
     * [See more information about frequency and presence penalties.](/docs/guides/text-generation/parameter-details)
     *
     */
    presencePenalty?: number | null | undefined;
    /**
     * An object specifying the format that the model must output. Compatible with [GPT-4 Turbo](/docs/models/gpt-4-and-gpt-4-turbo) and all GPT-3.5 Turbo models newer than `gpt-3.5-turbo-1106`.
     *
     * @remarks
     *
     * Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is valid JSON.
     *
     * **Important:** when using JSON mode, you **must** also instruct the model to produce JSON yourself via a system or user message. Without this, the model may generate an unending stream of whitespace until the generation reaches the token limit, resulting in a long-running and seemingly "stuck" request. Also note that the message content may be partially cut off if `finish_reason="length"`, which indicates the generation exceeded `max_tokens` or the conversation exceeded the max context length.
     *
     */
    responseFormat?: ResponseFormat | undefined;
    /**
     * This feature is in Beta.
     *
     * @remarks
     * If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.
     * Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
     *
     */
    seed?: number | null | undefined;
    /**
     * Up to 4 sequences where the API will stop generating further tokens.
     *
     * @remarks
     *
     */
    stop?: string | Array<string> | null | undefined;
    /**
     * If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://cookbook.openai.com/examples/how_to_stream_completions).
     *
     * @remarks
     *
     */
    stream?: boolean | null | undefined;
    /**
     * Options for streaming response. Only set this when you set `stream: true`.
     *
     * @remarks
     *
     */
    streamOptions?: ChatCompletionStreamOptions | null | undefined;
    /**
     * What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
     *
     * @remarks
     *
     * We generally recommend altering this or `top_p` but not both.
     *
     */
    temperature?: number | null | undefined;
    /**
     * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
     *
     * @remarks
     *
     * We generally recommend altering this or `temperature` but not both.
     *
     */
    topP?: number | null | undefined;
    /**
     * A list of tools the model may call. Currently, only functions are supported as a tool. Use this to provide a list of functions the model may generate JSON inputs for. A max of 128 functions are supported.
     *
     * @remarks
     *
     */
    tools?: Array<ChatCompletionTool> | undefined;
    /**
     * Controls which (if any) tool is called by the model.
     *
     * @remarks
     * `none` means the model will not call any tool and instead generates a message.
     * `auto` means the model can pick between generating a message or calling one or more tools.
     * `required` means the model must call one or more tools.
     * Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool.
     *
     * `none` is the default when no tools are present. `auto` is the default if tools are present.
     *
     */
    toolChoice?: ChatCompletionToolChoiceOption | undefined;
    /**
     * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
     *
     * @remarks
     *
     */
    user?: string | undefined;
    /**
     * Deprecated in favor of `tool_choice`.
     *
     * @remarks
     *
     * Controls which (if any) function is called by the model.
     * `none` means the model will not call a function and instead generates a message.
     * `auto` means the model can pick between generating a message or calling a function.
     * Specifying a particular function via `{"name": "my_function"}` forces the model to call that function.
     *
     * `none` is the default when no functions are present. `auto` is the default if functions are present.
     *
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    functionCall?: ChatCompletionFunctionCallOption | One | undefined;
    /**
     * Deprecated in favor of `tools`.
     *
     * @remarks
     *
     * A list of functions the model may generate JSON inputs for.
     *
     *
     * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
     */
    functions?: Array<ChatCompletionFunctions> | undefined;
};

/** @internal */
export namespace Two$ {
    export const inboundSchema = z.nativeEnum(Two);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Model$ {
    export const inboundSchema: z.ZodType<Model, z.ZodTypeDef, unknown> = z.union([
        z.string(),
        Two$.inboundSchema,
    ]);

    export type Outbound = string | string;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Model> = z.union([
        z.string(),
        Two$.outboundSchema,
    ]);
}

/** @internal */
export namespace CreateChatCompletionRequestType$ {
    export const inboundSchema = z.nativeEnum(CreateChatCompletionRequestType);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace ResponseFormat$ {
    export const inboundSchema: z.ZodType<ResponseFormat, z.ZodTypeDef, unknown> = z
        .object({
            type: CreateChatCompletionRequestType$.inboundSchema.default(
                CreateChatCompletionRequestType.Text
            ),
        })
        .transform((v) => {
            return {
                type: v.type,
            };
        });

    export type Outbound = {
        type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ResponseFormat> = z
        .object({
            type: CreateChatCompletionRequestType$.outboundSchema.default(
                CreateChatCompletionRequestType.Text
            ),
        })
        .transform((v) => {
            return {
                type: v.type,
            };
        });
}

/** @internal */
export namespace Stop$ {
    export const inboundSchema: z.ZodType<Stop, z.ZodTypeDef, unknown> = z.union([
        z.string(),
        z.array(z.string()),
    ]);

    export type Outbound = string | Array<string>;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Stop> = z.union([
        z.string(),
        z.array(z.string()),
    ]);
}

/** @internal */
export namespace One$ {
    export const inboundSchema = z.nativeEnum(One);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace CreateChatCompletionRequestFunctionCall$ {
    export const inboundSchema: z.ZodType<
        CreateChatCompletionRequestFunctionCall,
        z.ZodTypeDef,
        unknown
    > = z.union([ChatCompletionFunctionCallOption$.inboundSchema, One$.inboundSchema]);

    export type Outbound = ChatCompletionFunctionCallOption$.Outbound | string;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateChatCompletionRequestFunctionCall
    > = z.union([ChatCompletionFunctionCallOption$.outboundSchema, One$.outboundSchema]);
}

/** @internal */
export namespace CreateChatCompletionRequest$ {
    export const inboundSchema: z.ZodType<CreateChatCompletionRequest, z.ZodTypeDef, unknown> = z
        .object({
            messages: z.array(ChatCompletionRequestMessage$.inboundSchema),
            model: z.union([z.string(), Two$.inboundSchema]),
            frequency_penalty: z.nullable(z.number().default(0)),
            logit_bias: z.nullable(z.record(z.number().int())).optional(),
            logprobs: z.nullable(z.boolean().default(false)),
            top_logprobs: z.nullable(z.number().int()).optional(),
            max_tokens: z.nullable(z.number().int()).optional(),
            n: z.nullable(z.number().int().default(1)),
            presence_penalty: z.nullable(z.number().default(0)),
            response_format: z.lazy(() => ResponseFormat$.inboundSchema).optional(),
            seed: z.nullable(z.number().int()).optional(),
            stop: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
            stream: z.nullable(z.boolean().default(false)),
            stream_options: z.nullable(ChatCompletionStreamOptions$.inboundSchema).optional(),
            temperature: z.nullable(z.number().default(1)),
            top_p: z.nullable(z.number().default(1)),
            tools: z.array(ChatCompletionTool$.inboundSchema).optional(),
            tool_choice: ChatCompletionToolChoiceOption$.inboundSchema.optional(),
            user: z.string().optional(),
            function_call: z
                .union([ChatCompletionFunctionCallOption$.inboundSchema, One$.inboundSchema])
                .optional(),
            functions: z.array(ChatCompletionFunctions$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                messages: v.messages,
                model: v.model,
                frequencyPenalty: v.frequency_penalty,
                ...(v.logit_bias === undefined ? null : { logitBias: v.logit_bias }),
                logprobs: v.logprobs,
                ...(v.top_logprobs === undefined ? null : { topLogprobs: v.top_logprobs }),
                ...(v.max_tokens === undefined ? null : { maxTokens: v.max_tokens }),
                n: v.n,
                presencePenalty: v.presence_penalty,
                ...(v.response_format === undefined ? null : { responseFormat: v.response_format }),
                ...(v.seed === undefined ? null : { seed: v.seed }),
                ...(v.stop === undefined ? null : { stop: v.stop }),
                stream: v.stream,
                ...(v.stream_options === undefined ? null : { streamOptions: v.stream_options }),
                temperature: v.temperature,
                topP: v.top_p,
                ...(v.tools === undefined ? null : { tools: v.tools }),
                ...(v.tool_choice === undefined ? null : { toolChoice: v.tool_choice }),
                ...(v.user === undefined ? null : { user: v.user }),
                ...(v.function_call === undefined ? null : { functionCall: v.function_call }),
                ...(v.functions === undefined ? null : { functions: v.functions }),
            };
        });

    export type Outbound = {
        messages: Array<ChatCompletionRequestMessage$.Outbound>;
        model: string | string;
        frequency_penalty: number | null;
        logit_bias?: { [k: string]: number } | null | undefined;
        logprobs: boolean | null;
        top_logprobs?: number | null | undefined;
        max_tokens?: number | null | undefined;
        n: number | null;
        presence_penalty: number | null;
        response_format?: ResponseFormat$.Outbound | undefined;
        seed?: number | null | undefined;
        stop?: string | Array<string> | null | undefined;
        stream: boolean | null;
        stream_options?: ChatCompletionStreamOptions$.Outbound | null | undefined;
        temperature: number | null;
        top_p: number | null;
        tools?: Array<ChatCompletionTool$.Outbound> | undefined;
        tool_choice?: ChatCompletionToolChoiceOption$.Outbound | undefined;
        user?: string | undefined;
        function_call?: ChatCompletionFunctionCallOption$.Outbound | string | undefined;
        functions?: Array<ChatCompletionFunctions$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateChatCompletionRequest> = z
        .object({
            messages: z.array(ChatCompletionRequestMessage$.outboundSchema),
            model: z.union([z.string(), Two$.outboundSchema]),
            frequencyPenalty: z.nullable(z.number().default(0)),
            logitBias: z.nullable(z.record(z.number().int())).optional(),
            logprobs: z.nullable(z.boolean().default(false)),
            topLogprobs: z.nullable(z.number().int()).optional(),
            maxTokens: z.nullable(z.number().int()).optional(),
            n: z.nullable(z.number().int().default(1)),
            presencePenalty: z.nullable(z.number().default(0)),
            responseFormat: z.lazy(() => ResponseFormat$.outboundSchema).optional(),
            seed: z.nullable(z.number().int()).optional(),
            stop: z.nullable(z.union([z.string(), z.array(z.string())])).optional(),
            stream: z.nullable(z.boolean().default(false)),
            streamOptions: z.nullable(ChatCompletionStreamOptions$.outboundSchema).optional(),
            temperature: z.nullable(z.number().default(1)),
            topP: z.nullable(z.number().default(1)),
            tools: z.array(ChatCompletionTool$.outboundSchema).optional(),
            toolChoice: ChatCompletionToolChoiceOption$.outboundSchema.optional(),
            user: z.string().optional(),
            functionCall: z
                .union([ChatCompletionFunctionCallOption$.outboundSchema, One$.outboundSchema])
                .optional(),
            functions: z.array(ChatCompletionFunctions$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                messages: v.messages,
                model: v.model,
                frequency_penalty: v.frequencyPenalty,
                ...(v.logitBias === undefined ? null : { logit_bias: v.logitBias }),
                logprobs: v.logprobs,
                ...(v.topLogprobs === undefined ? null : { top_logprobs: v.topLogprobs }),
                ...(v.maxTokens === undefined ? null : { max_tokens: v.maxTokens }),
                n: v.n,
                presence_penalty: v.presencePenalty,
                ...(v.responseFormat === undefined ? null : { response_format: v.responseFormat }),
                ...(v.seed === undefined ? null : { seed: v.seed }),
                ...(v.stop === undefined ? null : { stop: v.stop }),
                stream: v.stream,
                ...(v.streamOptions === undefined ? null : { stream_options: v.streamOptions }),
                temperature: v.temperature,
                top_p: v.topP,
                ...(v.tools === undefined ? null : { tools: v.tools }),
                ...(v.toolChoice === undefined ? null : { tool_choice: v.toolChoice }),
                ...(v.user === undefined ? null : { user: v.user }),
                ...(v.functionCall === undefined ? null : { function_call: v.functionCall }),
                ...(v.functions === undefined ? null : { functions: v.functions }),
            };
        });
}
