/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Session = {
    /**
     * The unique identifier for this session.
     */
    id?: string | undefined;
};

/** @internal */
export namespace Session$ {
    export const inboundSchema: z.ZodType<Session, z.ZodTypeDef, unknown> = z.object({
        id: z.string().optional(),
    });

    export type Outbound = {
        id?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Session> = z.object({
        id: z.string().optional(),
    });
}
